version: "3.3"
services:
    tpucontainer:
        image: coral
        container_name: coral
        build:
            dockerfile: Dockerfile
        privileged: true
        command: "python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg"
